version: "3.8"
services:
  mongodb:
    image : mongo:4.4.8
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    networks:
      - app-network
    restart: always
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/node-demo
      - PORT=8080
    restart: always
    networks:
      - app-network
    depends_on:
      - mongodb



networks:
  app-network:
    driver: bridge

